# Generated by Django 4.2.2 on 2023-08-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_member_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
